When I first began my bachelor’s degree at the University of Texas at Dallas, I felt directionless. I did not have a clear idea of what I wanted to do in life or how I could contribute to the world. Although I enjoyed programming, what drew me most to computer science was problem-solving and the mathematics behind it. A few summer outreach programs and high school elective courses had sparked my interest, but I did not have any opportunity to really develop these interests until later in my undergraduate degree.

During my first semester, I noticed a flyer for a faculty research talk. Out of curiosity, I attended expecting only a technical presentation, but what stayed with me was the conversations I had afterward with PhD students and postdocs. I had the chance to speak with them about their research, and they led me to further reading into virtual reality text entry. Shortly after, I approached Professor Jin-Ryong Kim and began working at the Multimodal Interactions Lab. Working at the MI Lab became the defining experience of my first year. That year, I learned how to design studies, analyze data, and had the opportunity to collaborate on projects. I coauthored two papers on text entry in virtual and augmented reality, one of which was published at ACM CHI 2025 and received an Honorable Mention. The work was exciting, but it was also challenging. It required a large time commitment. As a result, I often questioned whether I was prepared to contribute meaningfully and if research was my best path forward. Over time, I realized that in some way, I wanted to develop humanity's overall knowledge, and that work in that direction could ultimately improve our understanding of the world in new and potentially useful ways. I further learned to collaborate on research and to persist through uncertain research projects. 

At the same time, my coursework was opening new doors. I developed an interest in discrete mathematics, algorithms, and combinatorial optimization. I enjoyed the problem-solving aspect of these classes, but was curious about how it extended into modern research. Shifting from HCI to theory was a large shift—I went from running experiments in a lab to learning to read and write proofs. Under the mentorship of Professor Emily Fox, I wrote a survey on discrete fair division and began research on symmetric submodular function minimization. Slowly, I became more comfortable reading and producing theory work, and decided to pursue a PhD in this subject. 

Pursuing an accelerated two-year degree added another dimension of challenge. Although I had received a significant amount of credit through high school work, it was often still a challenge to work on both coursework and research in such a short period of time. Still, this gave me several opportunities to learn from senior and graduate students, and to work with people who knew much more than I did. 

Along the way, I discovered how much I enjoy teaching and mentoring. I founded the UTD Algorithms Club as an informal group where students could learn discrete math and algorithms by reading current research papers. I also worked as a grader for discrete mathematics, which gave me a structured way to support peers and further sharpen my ability to explain concepts clearly. These experiences confirmed that I want my future career to combine research with teaching, because sharing knowledge is as rewarding to me as creating it.

Looking back, I see that the various experiences I had as a student while doing research, including navigating transitions between fields, and accelerating my studies, have shaped not only my intellectual growth but also my perspectives on community. In a graduate community, I hope to contribute through research and teaching. I hope my experiences in teaching and mentorship through the algorithms club will assist me in teaching as a TA. While researching, I have often been much younger or less experienced than my peers in research. Thus, I know how meaningful it is when others mentor you and believe you can make a research contribution. I want to extend that same sense of belonging to others.

Ultimately, I began my undergraduate studies without a clear sense of direction, but I am leaving with both a love for research and a commitment to building inclusive communities around it. I hope to contribute to a community of research mentorship and research opportunities. These are the values I hope to bring to graduate school and to carry forward in an academic career.
