baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Iniyan Joseph'
theme = ['hugo-embed-pdf-shortcode', 'hugo-theme-nix']
enableInlineShortcodes = true

[params]
  Name = "Iniyan Joseph"
  HeaderUsername = "iniyan"
  HeaderHostname = "joseph"
  About = "My name is Iniyan Joseph. I am an undergraduate student at UTD studying Computer Science. I am interested in studying interesting problems in theoretical CS with direct real-world applications, especially discrete fair division (the division of a finite set of goods amongst a finite set of agents fairly). My current advisor is Professor Emily Fox at the Erik Jonsson School of Engineering and Computer Science at UTD. My prior work was in efficient text entry in virtual reality, under Professor Jin Ryong Kim at the Erik Jonsson School of Engineering and Computer Science at UTD. I will be graduating in Fall 2025, and plan to apply to PhD programs to begin in Spring 2026."
  ProfilePicture = "/HomecomingPicture.png"
  Email = "IIJ210000@utdallas.edu"
  GithubID = 'iniyanijoseph'
  LinkedInID = 'iniyanijoseph'

[menu]
  [[menu.header]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    
    # [[menu.header]]
    #   parent = "projects"
    #   name = "Project 1"
    #   url = "/posts"
    
  [[menu.header]]
    identifier = "music"
    name = "Music"
    url = "/music/"
  
  [[menu.header]]
    identifier = "other"
    name = "Other"
    url = "/other"
