baseURL: "https://iniyanijoseph.github.io/" 
title: Iniyan Joseph
pagination.pagerSize : 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags
menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Academics
          url: academics/
          weight: 3
        - name: Music
          url: music/
          weight: 4
        - name: Resume
          url: cv.pdf
          weight: 5
        - name: Timeline
          url: archive/
          weight: 6

params:
    description: "I am a CS graduate from the University of Texas at Dallas researching combinatorial optimization."
    author: Iniyan Joseph
    DateFormat: "Jan 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Iniyan Joseph
          subtitle: "I am a graduate of The University of Texas at Dallas, where I majored in Computer Science. I am interested in studying theoretical CS, especially combinatorial optimization. Currently, I am advised by Professor Emily Fox at the Siebel School of Computing and Data Science at The University of Illinois Urbana-Champaign, researching algorithms for symmetric submodular optimization. My prior work was in efficient text entry in virtual reality, under Professor Jin Ryong Kim at the Erik Jonsson School of Engineering and Computer Science at UTD. I am currently applying to PhD programs, and hope to begin in Fall 2026. I am also a part-time substitute teacher at Frisco ISD and part-time software engineer at ReviveXR, a Dallas startup developing VR therapeutics for seniors. Outside of work, I love playing piano, sports kiting, watching movies, and traveling to new places."
          imageUrl: "picture.jpg"
          imageWidth: 256
          imageHeight: 256
          imageTitle: Iniyan Joseph
          buttons:
            - name: Publications
              url: papers/
            - name: Projects
              url: projects/
            - name: Academics
              url: academics/
            - name: Music
              url: music/
            - name: Resume
              url: cv.pdf
    socialIcons:
        - name: Email
          url: mailto:iniyanijoseph@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=slTiJuQAAAAJ&hl=en
        - name: LinkedIn
          url: https://linkedin.com/in/iniyanijoseph
        - name: GitHub
          url: https://github.com/iniyanijoseph
        - name: ORCID
          url: https://orcid.org/0009-0008-8342-5755
      
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Iniyan Joseph"
      icon: picture.jpg # favicon.ico
      iconHeight: 18
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
