baseURL: "https://iniyanijoseph.github.io/" 
title: Iniyan Joseph
pagination.pagerSize : 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags
menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Music
          url: music/
          weight: 3
        - name: CV
          url: cv.pdf
          weight: 4

params:
    description: "I am a CS graduate from the University of Texas at Dallas researching combinatorial optimization."
    author: Iniyan Joseph
    DateFormat: "Jan 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Iniyan Joseph
          subtitle: "I am a graduate of The University of Texas at Dallas, where I majored in Computer Science. I am currently applying to PhD programs in Algorithms and Theory. Currently, I am advised by Professor Emily Fox at the Siebel School of Computing and Data Science at The University of Illinois Urbana-Champaign. My prior work was in efficient text entry in virtual reality, under Professor Jin Ryong Kim at the Erik Jonsson School of Engineering and Computer Science at UTD. I am currently applying to PhD programs, and hope to begin in Fall 2026. I am also a math teacher at KD College Prep."
          imageUrl: "picture.jpg"
          imageWidth: 256
          imageHeight: 256
          imageTitle: Iniyan Joseph
          buttons:
            - name: Publications
              url: papers/
            - name: Projects
              url: projects/
            - name: Music
              url: music/
            - name: CV
              url: cv.pdf
    socialIcons:
        - name: Email
          url: mailto:iniyanijoseph@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=slTiJuQAAAAJ&hl=en
        - name: LinkedIn
          url: https://linkedin.com/in/iniyanijoseph
        - name: GitHub
          url: https://github.com/iniyanijoseph
        - name: ORCID
          url: https://orcid.org/0009-0008-8342-5755
      
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Iniyan Joseph"
      icon: picture.jpg # favicon.ico
      iconHeight: 18
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
