#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])

The decision to graduate in two years was practical: my sister began college immediately after I finished my undergraduate degree, and accelerating my degree eased my family's financial burden. This pressure to graduate early pushed me to take large course loads throughout my undergraduate studies. This academic pressure became an exercise in resourcefulness, forcing me to identify valuable research opportunities quickly, build relationships with mentors, and find and create communities where I could learn through collaboration. By the end of my degree, I came to value how the challenge of graduating early while maintaining my research and community commitments had developed my resilience and shaped my approach to difficulty.

Managing this timeline while pursuing research, founding the Algorithms Club, and participating in competitive programming required persistence. Although it sometimes spread me thin, working across these areas despite my other commitments strengthened each pursuit. The most transformative part of my undergraduate years was experiencing collaborative problem-solving. In both my research and the Algorithms Club, I saw how bringing together people with different academic backgrounds and unique perspectives created deeper understanding for everyone and helped us solve problems more efficiently. Teaching algorithms through the club also fundamentally helped me become a better communicator and collaborator. To prepare each session, we read papers in both new and familiar areas of theoretical computer science, forcing us to engage with concepts outside our comfort zones. These discussions didn't just help other students—they exposed me to new perspectives that influenced my research directions.

This experience shaped my approach to mentorship. In the Multimodal Interactions Lab, when introducing new students to HCI literature and research tools, I helped them work collaboratively rather than solely on top-down instruction. In the Algorithms Club, I worked to make theoretical computer science accessible to students from computer science, mathematics, and other engineering disciplines, helping them connect algorithmic thinking to their own fields.

Working with people who approached problems differently—whether due to their disciplinary training, mathematical background, or research interests—consistently led to productive research discussions. As a graduate student, I'm eager to continue working across subdisciplines within theoretical computer science, to mentor students encountering new research areas, and to foster inclusive problem-solving communities. The persistence and resourcefulness I developed through my accelerated timeline will serve me well, but what I value most is the collaborative approach to research that emerged from working with others.

// One of the major challenges I faced during my undergraduate years was managing a heavy course load alongside my research commitments. Despite pushing myself to graduate within two years due to family financial challenges, I did research in both human computer interaction (HCI) and theory, founded and led an Algorithms Club, and participated in competitive programming. Since my sister began her undergrad immediately after I completed mine, I was able to relieve substantial financial pressure from my family by completing undergraduate coursework as a high schooler and accelerating my degree plan. At times managing this alongside pursuing my own goals in research spread me thin, but being persistent in each of these areas developed my focus and improved my abilities in each area. Though demanding, these experiences enabled me to contribute as a researcher while being proactive in seeking opportunities. In spite of my limited time as an undergraduate, I was able to find resources and experiences to make the most of these experiences.

// Having an active interest in research was the most transformative part of my undergraduate experience. Being involved in research gave me opportunities to work with a diverse community of postdocs, PhD students, and professors in theoretical CS and HCI. Working with others from diverse research interests helped me better understand and appreciate the breadth of HCI literature. Similarly, taking combinatorial optimization and working within theory helped me situate my fair division survey and work in optimization within the broader optimization literature and to better understand the mathematical motivation for such problems. As a graduate student I believe that my prior exposures across fields in computer science and the opportunity to work on coursework will provide me opportunities to both collaborate and mentor other students from diverse academic backgrounds. To me, these demonstrated the value of diversity in thought, and pushed me to encourage other students from nontraditonal backgrounds to pursue research. 

// My experience teaching students both economics and optimization through founding and leading the UTD Algorithms Club has given me the opportunity to work with others in different research areas and fields, and as a graduate student I will continue to work with others across niches in theory. Leading the algorithms club also gave me the opportunity to mentor students—whether from computer science, math, or other disciplines—introducing them to theory papers and helping them learn about recent algorithmic findings, especially in fair division and combinatorial optimization. Similarly, in the Multimodal Interactions Lab, I mentored students new to the lab, introducing them to HCI literature and to the tools we used for research. These opportunities allowed me to contribute to my community. The collaborative nature of these environments, especially the algorithms club, demonstrated to me firsthand how a variety of perspectives could help better develop the entire group's understanding of the problem.
 
// In my PhD, I seek a collaborative research community. As I develop my research focus, I believe that I can contribute as a researcher and TA to these same collaborative communities. I want to share my love for research with other younger students, and to with other researchers in different niches at the intersection of different areas. I am eager to contribute to an inclusive community where researchers with diverse backgrounds, experiences, and perspectives collaborate and support each other, just as I experienced during my undergraduate career.
