#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])
#show heading : it => align(center)[#it]
= Personal History Statement
One substantial challenge during my undergraduate years was managing a heavy course load alongside my research commitments. Despite graduating in two years because of financial pressure from my family, I balanced research in HCI and Theory CS and participation in clubs alongside schoolwork. Within that time, I was able to do research in both HCI and theory, founded and led an Algorithms Club and participated in competitive programming. Though demanding, these experiences enabled meaningful contributions as a researcher while maintaining active involvement in extracurricular commitments, and prepared me to continue to do so as a graduate student.

Taking an active interest in research became the most transformative part of my undergraduate experience. In my first semester, I attended several talks by visiting professors hosted by the department. These first exposures in research inspired me to attempt my own research, and I joined the Multimodal Interactions Lab. Being involved in research gave me opportunities to meet my peers involved in research, and to work with postdocs, PhD students, other undergraduates, and professors in Theoretical CS and HCI.

Although it was only my first year, working with others exposed me to perspectives on how their papers related to other work, and helped me better understand where my project fit within the broader literature. This has been true for both HCI and algorithms; for instance, taking combinatorial optimization helped me situate my fair division survey within the broader optimization literature and understand connections between seemingly diverse problems.

Being surrounded by these research communities motivated me to push myself intellectually. When it came time to publish papers, it was these same communities that guided me in developing my writing abilities.  Involvement in competitive programming from my first semester exposed me to diverse algorithmic paradigms and sparked my interest in theoretical computer science. Combined with the mentorship I received in research, this inspired me to create similar opportunities for other students. I founded the Algorithms Club at UTD to introduce students to theory papers and helped them learn about recent algorithmic findings, especially in fair division and online algorithms. Similarly, in the Multimodal Interactions Lab, I mentored students new to the lab, introducing them to HCI literature and introduced them to the tools we used for research. 

In my PhD, I seek to find this same kind of community within algorithms and theoretical computer science. As I develop my research focus, I hope to be surrounded by people working across the different areas within algorithms like online algorithms, economics, and combinatorial optimization. I want to work with scholars who help me see unexpected connections and collaborate on problems at the intersection of different areas within algorithms. I will contribute to a community where researchers with different expertise can collaborate with each other, just as I am grateful to have experienced during my undergraduate career.
