#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])

Through a PhD in Computer Science focusing on theory and algorithms, I seek to research the structure of discrete optimization problems and design algorithms for them.

I began research in my first semester at the University of Texas at Dallas when I joined the Multimodal Interactions Lab headed by Professor Jin-Ryong Kim. I worked on two papers on text entry using thumbs in virtual and augmented reality. In the first paper, we investigated virtual reality (VR) thumb typing in the air, developed techniques to address its challenges and measured their impact on performance. I ran studies and created new evaluation strategies based on prior work on spatial perception in VR. This paper is currently under submission. One of the central challenges of augmented reality text entry was the lack of passive physical feedback, leading to reduced typing performance. To address this, we worked on _Proptype: Everyday Props as Typing Surfaces in Augmented Reality_, which allows users to type on the surfaces of everyday objects, reducing fatigue while simulating the elimination of the need for external hardware. I designed and conducted user studies to evaluate the interface, and wrote the portions describing the studies and methodology. This paper was published in ACM CHI 2025 and received an Honorable Mention. In both projects, I also helped write the related works section and organize the relevant literature. These projects taught me to read and apply existing research and introduced me to writing academic content and the research process.

While I enjoyed researching within human computer interaction, I realized that I wanted to contribute to more fundamental, broadly applicable problems throughout my career. As I gained more exposure to discrete mathematics, data structures, and algorithms, I developed a deeper interest in theoretical computer science. To explore this research area further, I undertook an independent study with Professor Emily Fox. In the independent study, I read several fair division papers discussing different fairness notions, structural results, and algorithms, and learned about many of the open problems in the field. I also wrote a survey paper on fair division. This experience helped me become comfortable reading and synthesizing theory papers while introducing me to broader themes in optimization problems, and refined my academic writing ability.

Building on this, I began a project with Professor Fox on algorithms for symmetric submodular function minimization, which generalizes undirected global minimum cut beyond hypergraphs. While the fastest known algorithm for hypergraphs runs in superquadratic time using randomization, the fastest known algorithm for symmetric submodular functions requires cubic time. This motivated us to investigate the properties of symmetric submodular functions under various operations, and whether similar algorithms may apply. This work strengthened my mathematical foundations and introduced me to the process of theory research: I designed potential solutions to the problem, and helped prove and disprove conjectures. I also took a course on combinatorial optimization, where I learned how structural properties of problems guide algorithmic design, which helped me in my research and exposed me to new techniques and ideas. I loved my exposure to theory, the open-ended nature of working on these problems, and the creative thinking needed. These experiences confirmed my desire to pursue graduate study, and to research and develop my skill as a researcher while contributing to theoretical computer science.

Beyond research, I sought opportunities to teach and share my enthusiasm for theory. I founded the UTD Algorithms Club, an unofficial student group where I taught students the foundations of discrete mathematics and algorithms and hosted guided paper readings. I also worked as a grader for discrete mathematics, which gave me further opportunities to mentor students. Currently, I teach students in high school mathematics at KD College Prep, alongside working part-time at ReviveXR, a Dallas-based startup developing therapeutics for seniors using commercially available VR devices. These opportunities have given me a deep appreciation for teaching and mentoring in addition to research, and have reinforced my desire to pursue a career in academia. I look forward to the opportunity to work as a TA in graduate study, and I hope to make an impact as a teacher.

At The University of Texas at Dallas, I am excited to work with Professor Benjamin Raichel on geometric optimization. I am eager to research algorithms for metric embeddings and other optimization problems, and to continue researching at the university. I believe that my prior research and work in theory will make me a strong graduate student.

During my undergraduate studies, I conducted research in both HCI and theoretical computer science, collaborated with faculty and peers, and began defining my research interests. This work solidified my commitment to pursuing higher education and reinforced my desire to conduct research in a collaborative academic environment. Through graduate school and an academic career, I hope to be exposed to and challenged by new ideas from diverse perspectives, and to mentor the next generation of students.
