#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])
#show heading : it => align(center)[#it]
= Statement of Purpose
I hope to pursue a PhD in Computer Science focusing on theory and algorithms. Through my PhD, I want to create useful algorithms and develop our understanding of the structure of various optimization problems.

I began conducting research in my first semester at the University of Texas at Dallas when I joined the Multimodal Interactions Lab headed by Professor Jin-Ryong Kim. There, I wrote two papers on text entry using thumbs in virtual and augmented reality: the first is currently under submission, and the second, _Proptype: Everyday Props as Typing Surfaces in Augmented Reality_, was published in ACM CHI 2025 and received an Honorable Mention. In the first paper, we investigated virtual reality thumb typing in the air. Thumb typing strategies in virtual and augmented reality can reduce fatigue compared to other in-air strategies, and leverage familiar hand motions, but are constrained by spatial perception errors and limited speed. We developed techniques to address these challenges and measured their impact on performance. I contributed to this paper by running studies and creating new evaluation strategies based on prior work on perception in VR. Proptype explores another central challenge of text entry in AR: the lack of passive physical feedback, which can lead to muscle fatigue. A common solution is the use of external controllers, but these can interrupt natural interactions with other objects in the environment. Our approach allowed users to type on the surfaces of everyday objects, reducing fatigue while simulating eliminating the need for external hardware. My role focused on designing and conducting user studies to evaluate the interface. As a result, I also contributed to writing the portions describing the studies and methodology. I also helped write the related works section and organize the relevant literature for these projects. Through these experiences, I learned how to extract key insights from existing research and apply them to novel designs. Additionally, they introduced me to reading and writing academic content and the research process. 

While I enjoyed HCI, as I gained more exposure to discrete mathematics, data structures, and algorithms, I came to have a deeper interest in theoretical computer science. I was interested in the elegance and structure of algorithms and their potential applications, and wanted to pursue research in this area. To bridge my interests, I undertook an independent study with Professor Emily Fox. This experience helped me gain comfort reading and synthesizing theory papers, while introducing me to broader themes in optimization problems and some of the research in that area. This project also helped me develop my academic writing ability, culminating in a survey paper on Discrete Fair Division.

Building on this, I began a project with Professor Fox on algorithms for symmetric submodular function minimization. This work, currently ongoing, strengthened my understanding of math and gave me an introduction to the process of theory research as a whole. I also took a course on combinatorial optimization, and these two experiences together highlighted how structural properties of problems guide algorithmic design. These experiences confirmed my desire to pursue theory research.

Beyond research, I have sought opportunities to teach and share my enthusiasm for theory. I founded the UTD Algorithms Club, an informal student group where I led sessions on discrete mathematics and algorithms. I also worked as a grader for discrete mathematics. Since graduating, I have been able to tutor students in high-school mathematics in addition to working part-time at ReviveXR, a Dallas-based startup developing therapeutics for seniors using commercially available VR devices. These experiences have given me deep appreciation for teaching and mentoring in addition to research, and they reinforced my long-term goal of pursuing a career in academia. 


In graduate study, I hope to focus on algorithms. At UC Irvine, I am especially interested in working with Professor Vijay Vazirani on problems in Fair Division and research the structure of envy-freeness and matching markets. I am also excited by the broader directions in optimization techniques and the structure of optimization problems, and by their applications to connectivity and online algorithms. I would be eager to contribute to this research community and explore new extensions of these problems.

Although I only spent two years completing my undergraduate degree, it provided me with opportunities to conduct research in both HCI and theoretical computer science, to collaborate with faculty and peers, and to begin defining my research interests. These experiences ultimately solidified my commitment to pursuing higher education and inspired me to conduct research in the future. I want to continue exploring algorithm design, contribute to theoretical CS research, and mentor the next generation of students. Through my PhD, I hope to explore algorithm design in various contexts and to gain deeper insights into mathematics and computer science as a whole.
