#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])
#show heading : it => align(center)[#it]
= Statement of Purpose
I hope to pursue a PhD in Computer Science focusing on algorithms for combinatorial optimization. Through my PhD, I want to create useful algorithms and develop our understanding of the structure of various optimization problems.

I began conducting research in my first semester at the University of Texas at Dallas when I joined the Multimodal Interactions Lab headed by Professor Jin-Ryong Kim. There, I wrote two papers on text entry in virtual and augmented reality. The second, _Proptype: Everyday Props as Typing Surfaces in Augmented Reality_, was published in ACM CHI 2025 and received Honorable Mention; the other is currently under submission. Proptype explores one of the central challenges of text entry in AR: the lack of passive physical feedback, which can lead to muscle fatigue while typing. A common solution is the use of external controllers, but these can interrupt natural interaction. Our approach allowed users to type on the surfaces of everyday objects, reducing fatigue while avoiding the need for external hardware. My role focused on designing and conducting user studies to evaluate the interface. As a result, I also contributed to writing the portions describing the studies and methodology. Through these two projects, I gained familiarity with the literature on thumb-typing and helped to write the related works and introduction sections. In the second project, we investigated thumb typing in VR. Mid-air typing strategies can reduce fatigue and leverage familiar hand motions, but are often constrained by spatial perception errors and limited speed. We developed techniques to address these challenges and measured their impact on performance. I contributed by running studies and creating new evaluation strategies based on prior work on perception in VR. I also helped write the related works section and organize the relevant literature for the project. Through this experience, I learned how to extract key insights from existing research and apply them to novel designs. Additionally, it introduced me to reading and writing academic content and the research process.

While I enjoyed HCI, as I gained more exposure to discrete mathematics, data structures, and algorithms, I came to have a deeper interest in theoretical computer science. I was interested in the elegance and structure of algorithms and their potential applications, and wanted to pursue research in this area. To bridge my interests, I undertook an independent study with Professor Emily Fox. This experience helped me gain comfort reading and synthesizing theory papers, while introducing me to broader themes in optimization problems and some of the research in that area. This project also helped me develop my academic writing ability, culminating in a survey paper on Discrete Fair Division.

Building on this, I began a project with Professor Fox on algorithms for symmetric submodular function minimization. This work, currently ongoing, has strengthened my understanding of math and gave me an introduction to the process of theory research as a whole. I also took a course on combinatorial optimization, and these two experiences together highlighted how structural properties of problems guide algorithmic design. These experiences confirmed my desire to pursue theory research.

Beyond research, I have sought opportunities to teach and share my enthusiasm for theory. I founded the UTD Algorithms Club, an informal student group where I led sessions on discrete mathematics and algorithms. I also worked as a grader for discrete mathematics. Since graduating, I have been able to tutor students in high-school mathematics in addition to working part-time at ReviveXR, a Dallas-based startup developing therapeutics for seniors using commercially available VR devices. These experiences have given me deep appreciation for teaching and mentoring in addition to research, and they reinforced my long-term goal of pursuing a career in academia. As a PhD student, I hope to work as a TA for the university.


In graduate study, I hope to focus on combinatorial optimization algorithms. At UC Irvine, I am especially interested in working with Professor Vijay Vazirani on problems in Fair Division and research the structure of envy-freeness and matching markets. I am also excited by the broader directions in optimization techniques and the structure of optimization problems, and by their applications to connectivity and online algorithms. I would be eager to contribute to this research community and explore new extensions of these problems.

Although I only spent two years completing my undergraduate degree, it provided me with opportunities to conduct research in both HCI and theoretical computer science, to collaborate with faculty and peers, and to begin defining my research interests. These experiences ultimately solidified my commitment to pursuing higher education and inspired me to conduct research in the future. I want to continue exploring algorithm design, contribute to theoretical CS research, and mentor the next generation of students. Through my PhD, I hope to explore algorithm design in various contexts and to gain deeper insights into mathematics and computer science as a whole.
