= An academic statement of up to 1,000 words addressing your plans for graduate study, including research interests, career goals, relevant coursework completed, and other educational experiences.
I am interested in pursuing a PhD in Combinatorial Optimization. I am fascinated by the mathematical connections between different optimization problems. Because of the breadth of applications to which optimization can be applied, I hope that further research into efficient algorithms for optimization problems can deepen our understanding of algorithms as a whole.

I began conducting research during my first semester at the University of Texas at Dallas, joining the Multimodal Interactions Lab under the guidance of Professor Jin-Ryong Kim. There, I wrote two papers on text entry in virtual and augmented reality. One, PropType: Everyday Props as Typing Surfaces in Augmented Reality, was published in ACM CHI 2025 and received an Honorable Mention; the other is currently under submission. PropType explores one of the central challenges of text entry in AR: the lack of passive physical feedback, which can lead to muscle fatigue. A common solution is the use of external controllers, but these can interrupt natural interaction. Our approach allowed users to type on the surfaces of everyday objects, reducing fatigue while avoiding the need for external hardware. My role focused on designing and conducting user studies to evaluate the interface. In the second project, we investigated thumb typing in VR. Mid-air typing strategies can reduce fatigue and leverage familiar hand motions, but are often constrained by spatial perception errors and limited speed. We developed techniques to address these challenges and measured their impact on performance. I contributed by running studies and creating new evaluation strategies based on prior work on perception in VR. Through this experience, I learned how to extract key insights from existing research and apply them to novel designs. Additionally, it introduced me to reading and writing academic content and the research process.

While I enjoyed HCI, my coursework in discrete mathematics, data structures, and algorithms sparked a deeper interest in theoretical computer science. I was fascinated by the elegance and structure of algorithms and wanted to pursue research in this area. To bridge my interests, I undertook an independent study with Professor Emily Fox, writing a survey on discrete fair division. This project helped me gain comfort reading and synthesizing theory papers, while introducing me to broader themes in matchings and combinatorial optimization.

Building on this, I began a project with Professor Fox on algorithms for symmetric submodular function minimization using randomized contractions. This work strengthened my mathematical maturity and deepened my familiarity with theoretical tools. I also took a graduate-level course on combinatorial optimization, which highlighted how structural properties of problems guide algorithmic design. Together, these experiences confirmed my desire to pursue combinatorial optimization research.

Beyond research, I have sought opportunities to teach and share my enthusiasm for theory. I founded the UTD Algorithms Club, an informal student group where I led sessions on discrete mathematics and algorithms. I also served as a grader for discrete mathematics. These experiences have shown me how much I enjoy teaching and mentoring, and they reinforced my long-term goal of pursuing an academic career. As a PhD sudent, I hope to work as a TA for the university, and am interested in both teaching and researching after graduation.

In graduate study, I hope to focus on algorithm design for combinatorial optimization problems. At the University of Illinois Urbana-Champaign, I am especially interested in working with Professors Chandra Chekuri, Karthekayan Chandrasekeran, and Emily Fox. Professor Chekuri and Chandrasekeran’s work on min-max partitioning of hypergraphs and symmetric submodular functions is closely connected to my current project, particularly the challenge of extending min-max hypergraph $k$-partition techniques to symmetric submodular systems. I am also excited by the broader directions in submodularity and supermodularity, and by their applications to connectivity, online algorithms, and geometric optimization. I would be eager to contribute to this research community and explore new extensions of these problems.

Although I completed my undergraduate degree in two years, it provided me with opportunities to conduct research in both applied and theoretical computer science, to collaborate with faculty and peers, and to begin defining my research interests. These experiences ultimately solidified my commitment to pursuing higher education and inspired me to conduct future research. I want to continue exploring deep connections across problems, contribute to theoretical understanding, and mentor the next generation of students. I hope through my PhD to explore combinatorial optimization problems in various contexts and to explore deeper insights into mathematics and computer science as a whole.
---
= A personal statement addressing both of the following prompts (up to 1,000 words): \ Please describe any experiences and/or challenges that may have shaped your intellectual and personal development. \ Provide insight into your potential to contribute to a community of inclusion, belonging, and respect in which scholars with diverse perspectives, abilities, and experiences can learn and collaborate productively and positively.

When I first began my bachelor’s degree at the University of Texas at Dallas, I felt without direction. I did not have a clear idea of what I wanted to do in life, or how I could contribute to the world. Although I enjoyed programming, what drew me most to computer science was problem solving and the mathematics behind it. A few summer outreach programs and high school elective courses had sparked my interest, but I did not have any opportunity to really develop these interests until later in my undergraduate degree.

During my first semester, I noticed a flyer for a faculty research talk. Out of curiosity, I attended expecting only a technical presentation, but what stayed with me was the conversations I had afterward with PhD students and postdocs. I had the chance to speak with them about their research, and they lead me to further reading into virtual reality text entry. Shortly after, I approached Professor Jin-Ryong Kim and began working at the Multimodal Interactions Lab. Working at the MI Lab became the defining experience of my first year. That year I learned how to design studies, analyze data, and had the opportunity to collaborate on projects. I coauthored two papers on text entry in virtual and augmented reality, one of which was published at ACM CHI 2025 and received an Honorable Mention. The work was exciting, but it was also challenging. It required a large time commitment. As a result, I often questioned whether I was prepared to contribute meaningfully, and if research was my best path forward. Over time, I realized that in some way, I wanted to develop humanity's overall knowledge, and that work in that direction could ultimately improve our understanding of the world in new and potentially useful ways. I further learned to collaborate on research, and to persist through uncertain research projects. 

At the same time, my coursework was opening new doors. I developed an interest in discrete mathematics, algorithms, and combinatorial optimization. I enjoyed the problem solving aspect of these classes, but was curious about how it extended into modern research. Shifting from HCI to theory was a large shift—I went from running experiments lab to learning to read and write proofs. Under the mentorship of Professor Emily Fox, I wrote a survey on discrete fair division and began a research on symmetric submodular function minimization. Slowly, I became more comfortable reading and producing theory work, and decided to pursue a PhD in this subject. 

Pursuing an accelerated two-year degree added another dimension of challenge. Although I had recieved a significant amount of credit through high school work, it was often still a challenge to work on both coursework and research into such a short period of time. Still, this gave me several opportunities to learn from senior and graduate students, and to work with people who knew much more than me. 

Along the way, I discovered how much I enjoy teaching and mentoring. I founded the UTD Algorithms Club as an informal group where students could learn discrete math and algorithms by reading current research papers. I also worked as a grader for discrete mathematics, which gave me a structured way to support peers and further sharpen my ability to explain concepts clearly. These experiences confirmed that I want my future career to combine research with teaching, because sharing knowledge is as rewarding to me as creating it.

Looking back, I see that the various experiences I had as a student while doing research, including navigating transitions between fields, and accelerating my studies have shaped not only my intellectual growth but also my perspectives on community. In a graduate community, I hope to contribute through research and teaching. I hope my experiences in teaching and mentorship through the algorithms club will assist me in teaching as a student as a TA. While researching, I have often been much younger or less experienced than my peers in research. Thus, I know how meaningful it is when others mentor you and believe you can make a research contribution. I want to extend that same sense of belonging to others.
Ultimately, I began my undergraduate studies without a clear sense of direction, but I am leaving with both a love for research and a commitment to building inclusive communities around it. I hope to contribute to a community of research mentorship and research opportunities. These are the values I hope to bring to graduate school and to carry forward in an academic career.
