#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])
#show heading : it => align(center)[#it]
= Statement of Purpose
I seek to pursue a PhD in Computer Science focusing on theory and algorithms. Through my PhD, I seek to research the structure of discrete optimization problems and design algorithms for them.

I began research in my first semester at the University of Texas at Dallas when I joined the Multimodal Interactions Lab headed by Professor Jin-Ryong Kim. I worked on two papers on text entry using thumbs in virtual and augmented reality: the first is under submission, and the second, _Proptype: Everyday Props as Typing Surfaces in Augmented Reality_, was published in ACM CHI 2025 and received an Honorable Mention. In the first paper, we investigated virtual reality thumb typing in the air, developed techniques to address its challenges and measured their impact on performance. I contributed to this paper by running studies and creating new evaluation strategies based on prior work on spatial perception in VR. Proptype explores another central challenge of text entry in AR: the lack of passive physical feedback, which can lead to muscle fatigue. Our work allowed users to type on the surfaces of everyday objects, reducing fatigue while simulating the elimination of the need for external hardware. My role focused on designing and conducting user studies to evaluate the interface, and I contributed to writing the portions describing the studies and methodology. For these projects, I also helped write the related works section and organize the relevant literature. These projects taught me to read and apply existing research and introduced me to writing academic content and the research process.

While I enjoyed HCI, as I gained more exposure to discrete mathematics, data structures, and algorithms, I developed a deeper interest in theoretical computer science. To explore this research area further, I undertook an independent study with Professor Emily Fox studying fair division the set of optimization problems related to partitioning goods among agents with heterogeneous preferences "fairly". In the independent study, I read over fifty papers discussing different fairness notions and learned about many of the open problems in the field. This culminated in writing a survey paper on the subject. This experience helped me become comfortable reading and synthesizing theory papers while introducing me to broader themes in optimization problems, and refined my academic writing ability.

Building on this, I began a project with Professor Fox on algorithms for symmetric submodular function minimization. Symmetric submodular function minimization is a generalization of the undirected global minimum cut problem. The fastest known exact algorithm for minimization of this structure requires cubic time, polynomially slower than the fastest known algorithm for hypergraphs using randomization. This motivated us to investigate the properties of symmetric submodular functions under various operations, and whether similar algorithms may apply. Here I designed potential solutions to the problem, and helped prove and disprove conjectures. This work strengthened my mathematical foundations and introduced me to the process of theory research. I also took a course on combinatorial optimization, which taught me how structural properties of problems guide algorithmic design. These experiences confirmed my desire to pursue theory research.

Beyond research, I sought opportunities to teach and share my enthusiasm for theory. I founded the UTD Algorithms Club, an informal student group where I led sessions on discrete mathematics and algorithms. I also worked as a grader for discrete mathematics. Since graduating, I tutor students in high school mathematics in addition to working part-time at ReviveXR, a Dallas-based startup developing therapeutics for seniors using commercially available VR devices. These opportunities have given me a deep appreciation for teaching and mentoring in addition to research, and have reinforced my long-term goal of pursuing a career in academia. 

In graduate study, I intend to focus on algorithms. At New York University, I am especially interested in working with Professor Aaron Bernstein. His work on graph optimization particularly interests me, and I am eager to research maximum flows and other optimization problems. I am excited by the broader directions in optimization techniques and the structure of optimization problems, and by their applications to networks, economics, online algorithms, and geometry. I would be eager to contribute to this research community and explore new extensions of these problems.

My undergraduate degree provided me with opportunities to conduct research in both HCI and theoretical computer science, to collaborate with faculty and peers, and to begin defining my research interests. This work solidified my commitment to pursuing higher education and reinforced my desire to conduct research. Through my PhD and future career, I aim to advance algorithm design and theoretical CS, and to mentor the next generation of students.
