#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])
#show heading : it => align(center)[#it]
= Statement of Purpose
Through a PhD in Computer Science focusing on theory and algorithms, I seek to research the structure of discrete optimization problems and design algorithms for them.

I began research in my first semester at the University of Texas at Dallas when I joined the Multimodal Interactions Lab headed by Professor Jin-Ryong Kim. I worked on two papers on text entry using thumbs in virtual and augmented reality. In the first paper, we investigated virtual reality thumb typing in the air, developed techniques to address its challenges and measured their impact on performance. I ran studies and created new evaluation strategies based on prior work on spatial perception in VR. This paper is currently under submission. One of the central challenges of AR text entry was the lack of passive physical feedback, leading to reduced typing performance. To address this, we worked on _Proptype: Everyday Props as Typing Surfaces in Augmented Reality_, which allows users to type on the surfaces of everyday objects, reducing fatigue while simulating the elimination of the need for external hardware. I designed and conducted user studies to evaluate the interface, and wrote the portions describing the studies and methodology. This paper was published in ACM CHI 2025 and received Honorable Mention. In both projects, I also helped write the related works section and organize the relevant literature. These projects taught me to read and apply existing research and introduced me to writing academic content and the research process.

While I enjoyed HCI, as I gained more exposure to discrete mathematics, data structures, and algorithms, I developed a deeper interest in theoretical computer science. To explore this research area further, I undertook an independent study with Professor Emily Fox. In the independent study, I read several fair division papers discussing different fairness notions, structural results, and algorithms, and learned about many of the open problems in the field. I also wrote a survey paper on fair division. This experience helped me become comfortable reading and synthesizing theory papers while introducing me to broader themes in optimization problems, and refined my academic writing ability.

Building on this, I began a project with Professor Fox on algorithms for symmetric submodular function minimization, which generalizes undirected global minimum cut beyond hypergraphs. While the fastest known algorithm for hypergraphs runs in superquadratic time using randomization, the fastest known algorithm for symmetric submodular functions requires cubic time. This motivated us to investigate the properties of symmetric submodular functions under various operations, and whether similar algorithms may apply. This work strengthened my mathematical foundations and introduced me to the process of theory research: I designed potential solutions to the problem, and helped prove and disprove conjectures. I also took a course on combinatorial optimization. In the course, I learned how structural properties of problems guide algorithmic design, which helped me in my research and exposed me to new techniques and ideas in algorithm design. These experiences confirmed my desire to pursue theory research.

Beyond research, I sought opportunities to teach and share my enthusiasm for theory. I founded the UTD Algorithms Club, an unofficial student group where I taught students the foundations of discrete mathematics and algorithms and hosted guided paper readings. I also worked as a grader for discrete mathematics, which gave me further opportunities to mentor students. Currently, I teach students in high school mathematics at KD College Prep, in addition to working part-time at ReviveXR, a Dallas-based startup developing therapeutics for seniors using commercially available VR devices. These opportunities have given me a deep appreciation for teaching and mentoring in addition to research, and have reinforced my desire to pursue a career in academia. 

At Purdue, I am excited to work with Professor Quanrud on graph optimization, and with Professor Psomas on fair division and online algorithms. Their work aligns with my interests and prior research. I am excited by the broader directions in optimization techniques and the structure of optimization problems and am eager to contribute to this research community and explore new extensions of these problems.

In my undergraduate degree, I conducted research in both HCI and theoretical computer science, collaborated with faculty and peers, and began defining my research interests. This work solidified my commitment to pursuing higher education and reinforced my desire to conduct research in a collaborative academic environment. Through researching and teaching, I aim to advance algorithm design and theoretical CS, and to mentor the next generation of students.
