#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])
#show heading : it => align(center)[#it]
= Personal History Statement
One of the biggest challenges during my undergraduate years was managing a substantial course load alongside research commitments. Despite graduating in two years because of financial pressure, I was able to balance research opportunities and participation in clubs alongside schoolwork. Within that time, I was able to do research in both HCI and theory, founded and led an Algorithms Club and participated in competitive programming. Though demanding, this experience was deeply rewarding and prepared me to handle the challenges of graduate research.

Taking an active interest in research became the most transformative part of my undergraduate experience. Being on campus gave me opportunities to attend talks, meet other research students, and most importantly, to work with postdocs, PhD students, other undergraduates, and professors across various research areas. Although I was relatively new to research, working with others exposed me to new perspectives on how their papers related to other work, and helped me better understand where my project fit within the broader literature. This has been true for both HCI and algorithms; for instance, taking combinatorial optimization helped me situate my fair division survey within the broader optimization literature and understand connections between seemingly diverse problems.

Being surrounded by these research communities motivated me to push myself intellectually. When it came time to publish papers, it was this same community that guided me in developing my writing abilities. Early involvement in competitive programming exposed me to diverse algorithmic paradigms and sparked my interest in theoretical computer science. Combined with the mentorship I received in research, this inspired me to create similar opportunities for other students. I founded the Algorithms Club at UTD to introduce students to theory papers and helped them learn about recent algorithmic findings, especially in fair division and online algorithms. Similarly, in the Multimodal Interactions Lab, I mentored students new to the lab, introducing them to HCI literature and the research process. I believe that this experience helped several students from both the club and lab take a deeper interest in research. 

In my PhD, I want to find this same kind of community within theoretical computer science. As I develop my research focus, I hope to be surrounded by people working across approximation algorithms, complexity theory, etc. —scholars who help me see unexpected connections and collaborate on problems at the intersection of these areas. I want to contribute to a community where researchers with different expertise support and challenge each other, just as I am grateful to have experienced during my undergraduate career.
