I am interested in pursuing a PhD in Theoretical Computer Science focusing on combinatorial optimization algorithms. I am fascinated by the mathematical connections between different optimization problems. Because of the breadth of applications to which optimization can be applied, I believe that further research into efficient algorithms for optimization problems can deepen our understanding of algorithms as a whole.

I began conducting research during my first semester at the University of Texas at Dallas, joining the Multimodal Interactions Lab under the guidance of Professor Jin-Ryong Kim. There, I wrote two papers on text entry in virtual and augmented reality. One, _PropType: Everyday Props as Typing Surfaces in Augmented Reality_, was published in ACM CHI 2025 and received an Honorable Mention; the other is currently under submission. PropType explores one of the central challenges of text entry in AR: the lack of passive physical feedback, which can lead to muscle fatigue. A common solution is the use of external controllers, but these can interrupt natural interaction. Our approach allowed users to type on the surfaces of everyday objects, reducing fatigue while avoiding the need for external hardware. My role focused on designing and conducting user studies to evaluate the interface. In the second project, we investigated thumb typing in VR. Mid-air typing strategies can reduce fatigue and leverage familiar hand motions, but are often constrained by spatial perception errors and limited speed. We developed techniques to address these challenges and measured their impact on performance. I contributed by running studies and creating new evaluation strategies based on prior work on perception in VR. Through this experience, I learned how to extract key insights from existing research and apply them to novel designs. Additionally, it introduced me to reading and writing academic content and the research process.

While I enjoyed working in Human Computer Interaction, my coursework in discrete mathematics and algorithms sparked a deeper interest in theoretical computer science. I was fascinated by the elegance and structure of algorithms and wanted to pursue research in this area. To bridge my interests, I undertook an independent study with Professor Emily Fox, writing a survey on discrete fair division. This project helped me gain comfort reading and synthesizing theory papers, while introducing me to broader themes in matchings and combinatorial optimization.

Building on this, I began a project with Professor Fox on algorithms for symmetric submodular function minimization using randomized contractions. This work strengthened my mathematical maturity and deepened my familiarity with theoretical tools. I also took a graduate-level course on combinatorial optimization, which highlighted how structural properties of problems guide algorithmic design. Together, these experiences confirmed my desire to pursue combinatorial optimization research.

Beyond research, I have sought opportunities to teach and share my enthusiasm for theory. I founded the UTD Algorithms Club, an informal student group where I led sessions on discrete mathematics and algorithms. I also served as a grader for discrete mathematics. These experiences have shown me how much I enjoy teaching and mentoring, and they reinforced my long-term goal of pursuing an academic career. As a PhD sudent, I hope to work as a TA for the university, and am interested in both teaching and researching after graduation.

In graduate study, I hope to focus on algorithm design for combinatorial optimization problems. At the University of Illinois Urbana-Champaign, I am especially interested in working with Professors Chandra Chekuri, Karthekayan Chandrasekeran, and Emily Fox. Professor Chekuri and Chandrasekeran’s work on min-max partitioning of hypergraphs and symmetric submodular functions is closely connected to my current project, particularly the challenge of extending min-max hypergraph $k$-partition techniques to symmetric submodular systems. I am also excited by the broader directions in submodularity and supermodularity, and by their applications to connectivity, online algorithms, and geometric optimization. I would be eager to contribute to this research community and explore new extensions of these problems.

Although I completed my undergraduate degree in two years, it provided me with opportunities to conduct research in both applied and theoretical computer science, to collaborate with faculty and peers, and to begin defining my research interests. These experiences ultimately solidified my commitment to pursuing higher education and inspired me to conduct future research. I want to continue exploring deep connections across problems, contribute to theoretical understanding, and mentor the next generation of students. I hope through my PhD to explore combinatorial optimization problems in various contexts and to explore deeper insights into mathematics and computer science as a whole.

