= Personal Statement
The ultimate goal of research is to make a positive impact on society. This motivates me to pursue a PhD in Economics and Computation (EC) following my Undergraduate degree. Specifically, I hope to research randomized approximation algorithms and fair division. 

When I first began my undergraduate degree at the University of Texas at Dallas, I researched efficient text entry in virtual and augmented reality(VR/AR) under Professor Jin-Ryong Kim, submitting two papers to top-tier venues (of which one was recently accepted into CHI). In the paper, I designed and conducted experiments, helped extract findings and based on this, propose future research directions. By doing so, I learned the basic skills required to research. Above all, it gave me the opportunity to test my limits as a researcher, and made me love being pushing the frontier of knowledge. It was at this point that I change my focus. 

I have been involved in competitive programming from my first semester, and have participated in ICPC Regionals and the Meta Hacker Cup. I enjoyed working with others to solve algorithmic problems, which motivated me to pursue research further in theoretical CS. Additionally, I enjoyed the applied nature of my research in Human Computer Interaction, and want to continue to study theoretical problems with the same pragmatism. This drew me to Fair Division, which I found to be both theoretically interesting and had widespread societal applications, and its uses in resolving political conflicts, item distribution, and estate division. I began an independent study with Professor Emily Fox at UTD to study this, ultimately writing a survey of discrete fair division. This helped me confirm my interest in algorithms and theoretical CS. In the future, I hope to take a more foundational approach to CS, while still working with real-world problems.

My various experiences in research have made me confident that I can develop the skillset required for the SUPERB program and eventually, a Ph.D. Additionally, the value of the work I am choosing to society, be it through Computational Geometry or Economics and Computation, motivate me to pursue greater heights in research as a computer scientist.

= A brief statement (no more than 250 words) of your research interests.
This past fall, I had the opportunity to conduct an independent study in Fair Division, which marked my first experience with theoretical computer science papers. Preparing to write my survey paper and engaging with the literature, alongside taking theory classes, allowed me to explore various approaches to the design and analysis of algorithms. Writing the survey paper this past semester also taught me to read and organize theory. Similarly, teaching theory through the UTD Economics and Computation club helped strengthen my foundations in this field. 

Through this process, I developed an interest in approximation algorithms. I especially want to work on approximate shape-matching problems in computational geometry, and approximate Fischer market equilibrium computation. 

In the upcoming semester, I will focus my research -on approximations for the continuous Fréchet distance, a measure of similarity between two linearly parameterized curves. If a dog and its owner are each walking along a curve, the Fréchet distance can be seen as the shortest possible length of the leash. My work will involve implementing and empirically testing approximation algorithms for the Fréchet distance, as well as developing new algorithms and heuristics for the approximate Fréchet distance.
