#set text(font: "New Computer Modern", size:12pt)
#set page(header: [#align(center)[Iniyan Joseph | Link: #underline(link("iniyanijoseph.github.io")) | Email: #underline(link("mailto:iniyanijoseph@gmail.com"))] #line(length: 100%)])
#show heading : it => align(center)[#it]
= Personal History Statement
One of the major challenges during my undergraduate years was managing a heavy course load alongside my research commitments. Despite challenging myself to graduate within two years due to financial pressures from my family, I did research in both HCI and theory, founded and led an Algorithms Club and participated in competitive programming. Though demanding, these experiences enabled me to contribute as a researcher while maintaining active involvement in extracurricular commitments, and prepared me to manage my time effectively and be proactive in seeking opportunities as a graduate student.

Taking an active interest in research was the most transformative part of my undergraduate experience. In my first semester, I attended several talks by visiting professors hosted by the department. This first exposure to research inspired me to attempt my own research, and motivated me to reach out to join the Multimodal Interactions Lab. As a member of the lab, I conducted HCI research, and wrote two papers. Being involved in research gave me opportunities to meet my peers involved in research, and to work with a diverse community of postdocs, PhD students, and professors in theoretical CS and HCI. Working with others from diverse academic backgrounds and interests exposed me to new perspectives, helping me better understand where my work on thumb typing fit within the broader HCI literature. Similarly, taking combinatorial optimization and working with Professor Emily Fox helped me situate my fair division survey and work in optimization within the broader optimization literature and to better understand the mathematical motivation to work on such problems.

Being surrounded by research communities and being exposed to new ideas motivated me to push myself intellectually. When it came time to publish papers, these same communities guided me in developing my writing abilities. Involvement in competitive programming from my first semester exposed me to diverse algorithmic paradigms and sparked my interest in theoretical computer science. I was inspired by the mentorship I received in research to create similar opportunities for other students from a variety of backgrounds who may not otherwise have been exposed to theoretical computer science. I founded the Algorithms Club at UTD to introduce students—whether from computer science, math, or other disciplines, and regardless of prior experience—to theory papers and helped them learn about recent algorithmic findings, especially in fair division and online algorithms. Similarly, in the Multimodal Interactions Lab, I mentored students new to the lab, introducing them to HCI literature and to the tools we used for research.

In my PhD, I seek to find a collaborative research community within algorithms and theoretical computer science. As I develop my research focus, I hope to be surrounded by people working across the different areas within algorithms like online algorithms, economics, and combinatorial optimization. I want to work with scholars who help me see unexpected connections and collaborate on problems at the intersection of different areas within algorithms. I am eager to contribute to an inclusive community where researchers with diverse backgrounds, experiences, and perspectives collaborate and support each other, just as I am grateful to have experienced during my undergraduate career.
